name: computer-vision-tool
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ffmpeg
  - pip
  - pip:
    - streamlit>=1.39.0
    - mediapipe==0.10.9
    - protobuf==3.20.3
    - numpy<2.0.0
    - pandas
    - Pillow
    - requests
    - streamlit-webrtc
    # - av  # Installed via Condareamlit-lottie
    - av
    - aiortc
    - aioice
    - opencv-python-headless
    # - protobuf<4.0.0  # Let pip resolve protobuf to avoid conflicts
