name: computer-vision-tool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - av
  - pip
  - pip:
    - streamlit>=1.39.0
    - mediapipe
    - protobuf
    - numpy<2.0.0
    - pandas
    - Pillow
    - requests
    - streamlit-webrtc
    - streamlit-lottie
    - aiortc
    - aioice
    - opencv-python-headless
